#!/usr/bin/env python

import os

#from waflib.extras import symwaf2ic
#from waflib.extras.gtest import summary


def depends(ctx):
    pass


def options(opt):
    opt.load('pytest')
    opt.load('post_task')


def configure(cfg):
    cfg.load('pytest')
    cfg.load('post_task')


def build(bld):
    exclude_tests = []
    if not bld.env.post_sim:
        # do not test simulation if --without-sim was set
        exclude_tests.append("test_helpers_sim.py")
    bld(
        name='pycake_tests',
        tests=bld.path.ant_glob('test_*.py', excl=exclude_tests),
        features='pytest post_task',
        use=['pycalibtic', 'calibtic_xml',
             'pyredman', 'redman_xml',
             'pyhalbe_tests', 'pysthal_tests', 'sim_denmem_ts'],
        pythonpath=['..'],
        install_path=os.path.join('bin', 'tests', 'cake')
    )

    datadir = os.path.abspath(os.path.join(bld.options.prefix, 'share'))
    datadirsrc = bld.path.find_dir('share')
    bld.install_files(
        datadir,
        files=datadirsrc.ant_glob('**/*'),
        cwd=datadirsrc,
        relative_trick=True,
    )
